language: rust
addons:
  apt:
    packages:
      - libasound2-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
